export default {
    appName: "Candidate Dashboard",
    dashboard: "Dashboard",
    avatars: "Avatars",
    purchase: "Purchase",
    policy: "Policy",
    moderator: "Moderator",
    welcome: "Welcome, Candidate!",
    activeSessions: "Active Sessions",
    noSessions: "No active sessions. (Pre-launch)",
    avatarManagement: "Avatar Management",
    avatarPlaceholder: "Avatar management UI (pre-launch)",
    policyKnowledge: "Policy & Knowledge",
    policyPlaceholder: "Policy & knowledge base UI (pre-launch)",
    moderatorTools: "Moderator",
    moderatorPlaceholder: "Moderator tools UI (pre-launch)",
    version: "v0.1.0",
    language: "Language",
    english: "English",
    korean: "Korean",
    // Added for login and sidebar
    hostLogin: "Candidate Login",
    email: "Email",
    emailPlaceholder: "Enter your email",
    password: "Password",
    passwordPlaceholder: "Enter your password",
    login: "Log In",
    loggingIn: "Logging in...",
    logout: "Log Out",
    digitalTwinStudio: "Digital Twin Studio",
    createAvatarPersona: "Create New Avatar Persona",
    editAvatar: "Edit Avatar",
    avatarNamePlaceholder: "e.g., Candidate AI 1",
    voiceSamples: "Voice Samples",
    uploadVoiceRecordings: "Upload Voice Recordings (MP3/WAV)",
    highQualityAudio: "High-quality audio helps cloning fidelity",
    motionGesture: "Motion/Gesture",
    uploadMotionClip: "Upload Short Motion Clip (MP4)",
    createAndTrainAvatar: "Once ready, create and train the avatar to use it in sessions.",
    createAvatar: "Create Avatar",
    saveChanges: "Save Changes",
    avatarLibrary: "Avatar Library",
    activeAvatarCollections: "Active Avatar Collections",
    newAvatar: "New Avatar",
    statusReady: "Status: Ready",
    activate: "Activate",
    newPolicy: "New Policy",
    editPolicy: "Edit Policy",
    policyTitlePlaceholder: "Title",
    policyTagPlaceholder: "Tag (e.g., Economy)",
    policyDescPlaceholder: "Description",
    official: "Official",
    cancel: "Cancel",
    save: "Save",
    trigger: "Trigger",
    forbidden: "Forbidden",
    edit: "Edit",
    delete: "Delete",

    // Legacy review labels kept for reused translation keys
    evaluator: "Admin Review",
    evaluatorDescription: "Review pending candidate avatars.",
    approve: "Approve",
    reject: "Reject",
    rejectReason: "Reject reason (optional)",
    noPendingAvatars: "No pending avatars",
    noAvatars: "No avatars",
    loading: "Loading...",
    hostLabel: "Candidate",
    submittedLabel: "Submitted",
    statusLabel: "Status",
    allLabel: "All",
    draftLabel: "Draft",
    pendingLabel: "Pending",
    approvedLabel: "Approved",
    rejectedLabel: "Rejected",
    noActionsLabel: "No actions",
    viewLabel: "View",
    assetsLabel: "Assets",
    finalize: "Finalize",
    finalizeAll: "Finalize All",
    uploadingLabel: "Uploading",
    download: "Download",
    reviewedLabel: "Reviewed",
    avatarDetail: "Avatar Detail",

    // Figma dashboard & layout
    realtimeStatus: "Realtime Status",
    strategyAnalytics: "Strategy Analytics & Competitor Comparison",
    inboxQueue: "Unanswered Questions Queue (Inbox)",
    management: "Manage",
    testChat: "Test Chat",
    currentActiveAvatar: "Currently Active Avatar",
    noAvatarSelected: "No avatar selected",
    todayQuestions: "Today's Questions",
    learnedPolicyCards: "Learned Policy Cards",
    indexingStatus: "Indexing Status",
    unconfirmedInbox: "Unanswered Questions (Inbox)",
    planAndUsage: "Plan & Resource Usage",
    totalQuestions: "Total Questions",
    learnedDataRag: "Learned Data (RAG)",
    realtimeQuestionStatus: "Realtime Question Status",
    complete: "Complete",
    addedCount: "Added",
    needReview: "Needs Review",
    normal: "Normal",

    // Inbox
    inbox: "Unanswered Questions",
    inboxDescription: "Voter questions the AI couldn't answer or lacks data for.",
    filter: "Filter",
    batchProcess: "Batch Process",
    aiSuggestAnswer: "AI Suggest Answer",
    addAsPolicyCard: "Add as Policy Card",
    ignoreQuestion: "Ignore",
    similarQuestionCount: "{count} similar questions received",
    votersWaiting: "{count} voters waiting",
    questionsPilingUp: "Questions piling up?",
    questionsPilingUpDesc: "Upload new documents or use AI policy generation to make your avatar smarter.",
    goToKnowledge: "Go to Knowledge",
    priorityHigh: "High",
    priorityMedium: "Medium",
    priorityLow: "Low",
    priority: "Priority",

    // Analytics
    analytics: "Analytics",
    answerFeedback: "Answer Feedback",
    answerFeedbackAll: "All",
    answerFeedbackLiked: "Liked",
    answerFeedbackDisliked: "Disliked",
    answerFeedbackTotal: "Total voter reactions",
    answerFeedbackSearch: "Search questions, answers, users...",
    answerFeedbackEmpty: "No answer feedback yet",
    answerFeedbackQuestion: "Question",
    answerFeedbackAnswer: "Answer",
    answerFeedbackReason: "Reason",
    analyticsSelf: "My Candidate Analysis",
    analyticsComparison: "Competitor Comparison Battle",
    platformSupport: "Platform Positive Support Rate",
    districtRank: "District Popularity Rank",
    interestSource: "Voter Interest Entry Channels",
    searchTraffic: "Search Traffic",
    snsShare: "SNS Shares",
    policyPopularityRank: "My Policy Popularity Rank",
    voterReactionKeywords: "Voter Reaction Keywords",
    supportTrend: "Candidate Support Trend (AI Platform-based)",
    ourCandidate: "Our Candidate",
    competitorCandidate: "Competitor",
    gapIndicators: "Win/Lose Core Indicators (GAP)",
    supportGap: "Support Gap",
    avatarSatisfaction: "Avatar Response Satisfaction",
    urgentPolicyUpdate: "Urgent Policy Update Needed",
    topicShare: "Topic Share by Issue",
    topicShareDesc: "Which issues are voters asking whom about more?",
    advantage: "Advantage",
    disadvantage: "Disadvantage",
    contested: "Contested",
    aiStrategyGuide: "AI Competitive Edge Strategy Guide",
    todayMission: "Today's Mission",
    mentions: "mentions",

    // Avatar manager (Figma labels)
    avatarProfileGreeting: "Basic Profile & Greeting",
    avatarNameLabel: "Avatar Name",
    avatarNameExample: "e.g., Hong Gil-dong AI",
    partyLabel: "Affiliated Party",
    representativeGreeting: "Signature Opening Greeting",
    greetingPlaceholder: "First message voters will see when they enter the chat room.",
    systemPromptLabel: "AI Answer Guide (System Prompt)",
    systemPromptPlaceholder: "Enter the rules the AI should follow when responding.",
    candidateAppearance: "Candidate Appearance Data Capture",
    faceFrontPhoto: "Face Front Photo",
    faceFrontDesc: "Capture from the front with a neutral expression",
    faceSidePhoto: "Face Side Photo",
    faceSideDesc: "Capture at 45° left/right angles",
    fullBodyImage: "Full Body Image",
    fullBodyDesc: "Standing pose in a suit",
    freeGallery: "Free Gallery",
    freeGalleryDesc: "Candid shots (optional)",
    voiceAndMotion: "Voice & Gesture Motion",
    candidateVoiceData: "Candidate Voice Data (10+ minutes)",
    voiceUpload: "Upload Voice File",
    signatureMotion: "Signature Gesture Motion Video (15s or less)",
    motionUpload: "Upload Mobile Video",
    confirmDigitalTwin: "Confirm Candidate's Digital Twin",
    aiPersonaOptimize: "Optimize AI Persona",
    newPersonaCreate: "Create New Persona",
    avatarListTitle: "Owned Avatar List",
    displayName: "Display Name",
    description: "Description",
    promptLabel: "LLM System Prompt",
    promptHelp: "Instructions passed directly to the AI as the system prompt. Takes precedence over runtime settings.",
    promptPlaceholder: "You are an AI assistant named {name}. Respond in a professional and friendly manner...",
    profileJson: "Profile JSON",
    elevenlabsVoiceId: "ElevenLabs Voice ID",
    visibility: "Visibility",
    profileImage: "Profile Image",
    uploadImage: "Upload Image",
    assets: "Assets",
    uploadVoiceSample: "Upload Voice Sample",
    uploadMotion: "Upload Motion Clip",
    submitForReview: "Submit for Review",
    uploading: "Uploading...",
    openInNewTab: "Open in New Tab",
    active: "Active",

    // Policy (Figma)
    policyCards: "Policy Cards",
    documentsPdf: "Documents (PDF/Docs)",
    addDirect: "Add Directly",
    aiGeneratePolicies: "AI Auto-Generate Policy Cards",
    knowledgeUploadPdf: "Upload Knowledge Asset (PDF)",
    knowledgeUploadDesc: "Drag and drop PDF files to build the RAG knowledge source.",
    startIngest: "Start Ingest",

    // Extended avatar profile sections
    sectionGreeting: "Greeting",
    greetingHelp: "First greeting message shown when voters start a chat.",
    sectionCareer: "Career",
    sectionAchievements: "Achievements",
    sectionEducation: "Education",
    sectionAddress: "Address",
    sectionGeoRules: "Geo Rules",
    sectionBios: "Short Bios",
    sectionPledges: "Pledges",
    sectionMetadata: "Additional Metadata",
    addItem: "Add",
    removeItem: "Remove",
    dateFrom: "Start Date",
    dateTo: "End Date",
    descriptionLabel: "Description",
    iconLabel: "Icon",
    keyLabel: "Key / Label",
    titleLabel: "Title",
    detailsLabel: "Details",
    budgetLabel: "Estimated Budget",
    timelineLabel: "Timeline",
    beneficiariesLabel: "Beneficiaries",
    metadataJsonLabel: "Metadata (JSON)",
    country: "Country",
    state: "State/Province",
    city: "City",
    district: "District",
    addressLine1: "Address Line 1",
    addressLine2: "Address Line 2",
    postalCode: "Postal Code",
    latitude: "Latitude",
    longitude: "Longitude",
    formattedAddress: "Full Address",
    locationPreview: "Location Preview",
    locationPreviewHelp: "Looks up address details for the selected coordinates from the backend.",
    loadingLocationPreview: "Looking up address details…",
    addGeoRule: "Add Geo Rule",
    geoRuleCountryLabel: "State/Province",
    geoRuleCitiesLabel: "Cities (Optional)",
    geoRuleCountryPlaceholder: "Select a state/province",
    geoRuleCitiesPlaceholder: "Select a country first to load the city list.",
    geoRuleLoadingCities: "Loading city list…",
    geoRuleAppliesNationwide: "Leave empty to publish to the entire country.",
    geoRuleNoRestrictions: "No regional restrictions. Published worldwide.",
    noItems: "No items.",
    pending: "Pending",
    creating: "Creating…",
    saving: "Saving…",
    deleting: "Deleting…",
    finalizing: "Finalizing…",
    pendingReviewStage: "Pending review…",
    submittingForReview: "Submitting for review…",
    setPublic: "Set Public",
    setPrivate: "Set Private",

    // Multi-step avatar form tabs
    tabBasicInfo: "Basic Info",
    tabMedia: "Media & Files",
    tabProfile: "Profile",
    tabAddress: "Address",
    tabSubmit: "Review & Submit",

    // Tab save/create actions
    createDraftAndContinue: "Create Draft & Continue →",
    saveBasicInfo: "Save Basic Info",
    saveProfile: "Save Profile",
    saveAddress: "Save Address",
    savedSuccess: "Saved ✓",
    displayNameRequired: "Enter a display name",
    geoRulesTitle: "Avatar Geo Rules",
    geoRulesHelp: "Optional. Leave empty to allow without regional restrictions. You can narrow the scope by state/province and city/district in South Korea.",
    geoRulesRestrictedNote: "This avatar can only use a subset of the regional scope allowed for the candidate's account.",
    geoRulesRestrictedScopeHint: "The candidate's regional scope is restricted. Country-wide or city-wide allowance is only possible if the candidate's scope permits it.",
    geoRulesAddCountryPlaceholder: "Add state/province…",
    geoRulesAddCityPlaceholder: "Add city…",
    geoRulesAddDistrictPlaceholder: "Add district…",
    geoRulesEmptyState: "No regional restrictions. This avatar is available everywhere.",
    geoRulesRestrictedEmptyState: "Select at least one state/province or city/district within the candidate's regional scope.",
    geoRulesWholeCountry: "All cities/districts in this state/province are allowed.",
    geoRulesWholeCity: "All districts in this city are allowed.",
    geoRulesRequired: "Select at least one geo rule for this avatar.",
    geoRulesSelectCitiesRequired: "Select at least one city for this country.",
    geoRulesSelectDistrictsRequired: "Select at least one district for this city.",
    geoRulesNoCityOptions: "No selectable cities available",
    geoRulesNoDistrictOptions: "No selectable districts available",

    // Lock state
    lockedForReview: "This avatar is currently under review. Editing is locked until a decision is made.",
    lockedPublished: "This avatar is published. The review workflow restarts when edited.",
    publishedLockedBanner: "This avatar is published and editing is locked. Revert to draft to edit.",
    revertToDraftBtn: "Revert to Draft",
    revertToDraftConfirm: "Revert to draft?",
    revertToDraftDesc: "This takes the avatar offline and reverts it to draft status. You'll need to resubmit for review when ready.",
    revertToDraftConfirmBtn: "Yes, revert to draft",
    revertingToDraft: "Reverting to draft…",
    revertToDraftSuccess: "Avatar reverted to draft.",

    // Status labels
    statusDraft: "Draft",
    statusEvaluatorReview: "Under Admin Review",
    statusAdminReview: "Under Admin Review",
    statusPublished: "Published",
    statusRejected: "Rejected",
    statusEvaluatorApproved: "Admin Approved",

    // Submit tab
    submitTabTitle: "Review & Submit",
    submitTabDesc: "Submit your avatar for review when ready.",
    submitForReviewBtn: "Submit for Review",
    submitRequiresDisplayName: "Please set a display name before submitting.",
    currentStatus: "Current Status",
    underReviewMessage: "Avatar is currently under review. You'll be notified when a decision is made.",
    publishedMessage: "Avatar is published and visible to users.",
    evaluatorRejectionLabel: "Review rejection reason:",
    adminRejectionLabel: "Admin rejection reason:",
    rejectionReasonLabel: "Rejection reason:",
    assetRejectionReasonLabel: "Asset rejection reason:",

    // Rejection banner (shown on all tabs)
    rejectedBannerTitle: "Avatar Rejected — Action Needed",
    rejectedBannerDesc: "Review the reason below, make corrections, and resubmit.",

    // Reject modal (legacy review flow)
    rejectAvatarTitle: "Reject Avatar",
    rejectAssetTitle: "Reject Asset",
    rejectReasonRequired: 'Provide a rejection reason so the candidate can resolve the issue.',
    rejectReasonLabel: "Rejection Reason",
    rejectReasonPlaceholder: "Clearly explain what needs to be fixed…",
    rejectReasonErrorMsg: "Please enter a reason before rejecting.",
    rejectFile: "Reject File",

    // Media tab
    mediaTabDesc: "Upload media files for the avatar. Uploads are saved immediately.",

    // Knowledge tab
    tabKnowledge: "Knowledge Base",
    knowledgeTabDesc: "Add documents or text used to answer questions about this avatar.",
    addKnowledge: "Add Knowledge",
    knowledgeTitle: "Title",
    knowledgeTitlePlaceholder: "e.g., Product FAQ, Company intro…",
    knowledgeSourceType: "Source Type",
    knowledgeText: "Text Content",
    knowledgeTextPlaceholder: "Paste plain text here…",
    knowledgeFileUrl: "File URL (GCS object name)",
    knowledgeFileUrlPlaceholder: "e.g., knowledge/my-doc.pdf",
    knowledgeStatusPending: "Under Review",
    knowledgeStatusApproved: "Approved",
    knowledgeStatusRejected: "Rejected",
    knowledgeDelete: "Delete",
    knowledgeAdding: "Adding…",
    knowledgeDeleting: "Deleting…",
    knowledgeEmptyState: "No knowledge items yet. Add a document or text.",
    knowledgeAddSuccess: "Knowledge item submitted for review.",
    knowledgeDeleteSuccess: "Knowledge item deleted.",
    knowledgeErrorLoad: "Failed to load knowledge items.",
    knowledgeErrorAdd: "Failed to add knowledge item.",
    knowledgeErrorDelete: "Failed to delete knowledge item.",
    knowledgeApprove: "Approve",
    knowledgeReject: "Reject",
    knowledgeApproveSuccess: "Knowledge approved and added to the processing queue.",
    knowledgeRejectSuccess: "Knowledge rejected.",

    // News
    news: "News",
    newsCategoryMajorNews: "Major News",
    newsCategoryCandidate: "Candidate",
    newsCategoryPolicy: "Policy",
    newsCategoryRegion: "Region",
    newsDescription: "Manage and publish news displayed to voters.",
    newNews: "New News",
    editNews: "Edit News",
    noNews: "No news registered.",
    newsDeleteConfirm: "Delete this news item?",
    newsTitleLabel: "Title",
    newsTitlePlaceholder: "Enter news title",
    newsCategory: "Category",
    newsSummary: "Summary",
    newsSummaryPlaceholder: "Short summary shown in feed",
    newsContent: "Content",
    newsContentPlaceholder: "Full article body",
    newsSourceName: "Source Name",
    newsSourceUrl: "Source URL",
    newsImageUrl: "Cover Image",
    newsUploadImage: "Upload Cover Image",
    newsChangeImage: "Change Image",
    publishImmediately: "Publish Immediately",
    publish: "Publish",
    unpublish: "Unpublish",
    published: "Published",
    newsEnglishLabel: "English (EN)",
    newsKoreanLabel: "Korean (KO)",
    newsContentLanguage: "Content Language",
    newsTitleEnPlaceholder: "English title",
    newsTitleKoPlaceholder: "Korean title",
    newsSummaryEnPlaceholder: "Short summary (English)",
    newsSummaryKoPlaceholder: "Short summary (Korean)",
    newsContentEnPlaceholder: "Full article body (English)",
    newsContentKoPlaceholder: "Full article body (Korean)",
    newsLocaleRequired: "Fill in at least one of EN or KO.",

    // Candidate Avatar Studio
    candidateFallback: "Candidate",
    avatarStudioFallbackAvatarName: "Candidate Avatar",
    avatarStudioAvatarSuffix: "Avatar",
    avatarStudioDefaultPersonaFallbackName: "Candidate",
    avatarStudioIntroMessage: "The candidate avatar key rehearsal is ready. Test the persona by entering a policy or voter question.",
    avatarStudioDefaultPersonaTemplate: "You are {name}'s official digital avatar. Respond with clear civic perspective, practical next steps, and calm confidence.",
    avatarStudioVersionLog: "Avatar Version Log",
    avatarStudioStartNewVersion: "Start New Avatar Version",
    avatarStudioLoadingVersions: "Loading version list...",
    avatarStudioNoAvatarYet: "No avatar created yet. Create your first avatar version.",
    avatarStudioVersion: "Version",
    avatarStudioLabel: "Avatar Model Studio",
    avatarStudioRegistration: "Avatar Registration",
    avatarStudioDescription: "Versioned avatar editing workspace for the candidate evolution flow.",
    avatarStudioMakePrivate: "Make Private",
    avatarStudioMakePublic: "Make Public",
    avatarStudioPublishing: "Publishing...",
    avatarStudioPublishNow: "Publish Now",
    avatarStudioSaving: "Saving...",
    avatarStudioSave: "Save",
    avatarStudioTabAvatar: "Avatar",
    avatarStudioTabPersona: "Persona Training",
    avatarStudioTabQuestions: "Unanswered Questions",
    avatarStudioCharacterImage: "1. Character Image",
    avatarStudioNoPreview: "No preview",
    avatarStudioUploadImage: "Upload Image",
    avatarStudioImagePortraitTitle: "Portrait Image",
    avatarStudioImagePortraitCaption: "Syncs with the real-time avatar profile image.",
    avatarStudioImageCampaignTitle: "Campaign Reference Image",
    avatarStudioImageCampaignCaption: "Visual reference image for design iteration work.",
    avatarStudioImageCloseupTitle: "Close-up Reference Image",
    avatarStudioImageCloseupCaption: "Additional face angle sample for styling reviews.",
    avatarStudioRegistrationDetails: "Avatar Registration Details",
    avatarStudioAvatarName: "Avatar Name",
    avatarStudioOpeningMessage: "Opening Message",
    avatarStudioOpeningMessagePlaceholder: "Greeting shown on first interaction",
    avatarStudioVisibility: "Visibility",
    avatarStudioVoiceId: "ElevenLabs Voice ID",
    avatarStudioOptionalVoiceOverride: "Optional voice override",
    avatarStudioVoiceManagedExternally: "Voice settings are managed externally from the candidate dashboard.",
    avatarStudioPublishedHint: "Saving a published version creates a new editable draft for additional edits.",
    avatarStudioDraftHint: "Draft changes remain in the candidate's workspace and can be published immediately after internal approval.",
    avatarStudioSyncedImage: "Synced Portrait Image",
    avatarStudioProfileImageFallback: "Profile Image",
    avatarStudioVoiceLearning: "2. Voice Training",
    avatarStudioVoiceSample: "Voice Sample",
    avatarStudioNoFileUploaded: "No file uploaded",
    avatarStudioUploading: "Uploading...",
    avatarStudioUploadVoiceSample: "Upload Voice Sample",
    avatarStudioSignatureMovement: "3. Signature Movement",
    avatarStudioMotionClip: "Motion Clip",
    avatarStudioUploadMovementClip: "Upload Movement Clip",
    avatarStudioDelete: "Delete",
    avatarStudioDefaultPersonaSettings: "Default Persona Settings",
    avatarStudioCorePersona: "Core Persona",
    avatarStudioCorePersonaPlaceholder: "Define the candidate's tone, policy boundaries, and answer rules.",
    avatarStudioAnswerTone: "Answer Tone",
    avatarStudioSpeechStyle: "Speech Style",
    avatarStudioSpeechStylePlaceholder: "Short, practical public-service style answers",
    avatarStudioSpeechStyleDefault: "Short, practical civic-guide style answers",
    avatarStudioToneConfidentWarm: "Confident and warm tone",
    avatarStudioToneFormalPolicyHeavy: "Formal and policy-focused",
    avatarStudioToneFriendlyConcise: "Friendly and concise tone",
    avatarStudioToneDebateReadyAssertive: "Debate-ready, assertive tone",
    avatarStudioNegativeLearning: "Negative Training Material",
    avatarStudioNegativeLearningHelp: "Define content the avatar should avoid or sidestep.",
    avatarStudioAddGuardrail: "Add Guardrail",
    avatarStudioAdd: "Add",
    avatarStudioNegativeTagPersonalAttacks: "Avoid personal attacks",
    avatarStudioNegativeTagInventStats: "Don't fabricate statistical figures",
    avatarStudioKnowledgeTitle: "Avatar Knowledge",
    avatarStudioKnowledgeDesc: "Upload or drag-and-drop PDF or Word documents for this avatar to use, or add text knowledge directly.",
    avatarStudioKnowledgeFilePick: "PDF or DOCX files, multi-select supported",
    avatarStudioKnowledgeFileDrop: "Drag or click to upload documents",
    avatarStudioKnowledgeFileDropActive: "Drop files here to upload",
    avatarStudioKnowledgeUploadedDocument: "Uploaded Document",
    avatarStudioKnowledgeAddMore: "Add",
    avatarStudioKnowledgeTextPlaceholder: "Enter basic knowledge like pledges, background, key strengths, regional focus...",
    avatarStudioKnowledgeTextAction: "Add Knowledge",
    avatarStudioKnowledgeTextRequired: "Text content",
    avatarStudioKnowledgeTextFallbackTitle: "Avatar Knowledge Note",
    avatarStudioKnowledgeAddSuccess: "Knowledge item added and indexed.",
    avatarStudioKnowledgeDeleteSuccess: "Knowledge item deleted.",
    avatarStudioKnowledgeErrorAdd: "Failed to add knowledge.",
    avatarStudioKnowledgeErrorDelete: "Failed to delete knowledge.",
    avatarStudioKnowledgeErrorLoad: "Failed to load knowledge items.",
    avatarStudioKnowledgeUnsupportedFile: "Only PDF and DOCX files can be uploaded.",
    avatarStudioKnowledgeCreateAvatarHint: "Create or save the avatar first before uploading training material.",
    avatarStudioKnowledgeLockedPublished: "Training material cannot be edited while the avatar is published.",
    avatarStudioKnowledgeLoading: "Loading…",
    avatarStudioKnowledgeEmptyState: "No knowledge items registered yet.",
    avatarStudioKnowledgeDelete: "Delete",
    avatarStudioKnowledgeDownload: "Download File",
    avatarStudioKnowledgeView: "View",
    avatarStudioKnowledgeHide: "Hide",
    avatarStudioKnowledgeUploading: "Uploading…",
    avatarStudioConversationRehearsal: "Conversation Rehearsal",
    avatarStudioTextMode: "Text",
    avatarStudioVoiceMode: "Voice",
    avatarStudioSampleQuestionPlaceholder: "Enter a sample voter question to test the persona",
    avatarStudioSend: "Send",
    avatarStudioQuestionInbox: "Question Inbox",
    avatarStudioAnswerDesign: "Answer Design",
    avatarStudioQuestion: "Question",
    avatarStudioReceivedFrom: "Received From",
    avatarStudioRecommendedAnswer: "Recommended Answer",
    avatarStudioRecommendedAnswerPlaceholder: "Write the answer the avatar should learn from this question.",
    avatarStudioRedirectNotes: "Negative / Redirect Notes",
    avatarStudioRedirectNotesPlaceholder: "Define content the avatar should avoid or situations to pass to the official team.",
    avatarStudioMarkAnswered: "Mark as Answered",
    avatarStudioIgnore: "Ignore",
    avatarStudioReset: "Reset",
    avatarStudioNoPendingQuestions: "No pending questions.",
    avatarStudioSourceLiveChat: "Live Chat Session",
    avatarStudioSourceCampaignSite: "Campaign Site Form",
    avatarStudioSourceModeratorQueue: "Moderator Queue",
    avatarStudioStatusPending: "Pending",
    avatarStudioStatusAnswered: "Answered",
    avatarStudioStatusIgnored: "Ignored",
    avatarStudioLoadAvatarsError: "Failed to load the avatar list.",
    avatarStudioLoadAvatarDetailError: "Failed to load avatar details.",
    avatarStudioCreatedNewVersion: "Created editable draft version {version} from the published avatar.",
    avatarStudioAvatarSaved: "Avatar saved.",
    avatarStudioSaveAvatarError: "Failed to save avatar.",
    avatarStudioAvatarPublished: "Avatar published.",
    avatarStudioPublishAvatarError: "Failed to publish avatar.",
    avatarStudioAvatarPublic: "Avatar is now public.",
    avatarStudioAvatarPrivate: "Avatar is now private.",
    avatarStudioToggleVisibilityError: "Failed to change visibility.",
    avatarStudioAssetUploaded: "Asset upload complete.",
    avatarStudioUploadAssetError: "Failed to upload asset.",
    avatarStudioAssetDeleted: "Asset deleted.",
    avatarStudioDeleteAssetError: "Failed to delete asset.",
    avatarStudioPreviewError: "Could not prepare file preview.",
    avatarStudioFilePreviewReadError: "Could not read file preview.",
    avatarStudioAssistantFallback: "Stay on the campaign policy direction.",
    avatarStudioFocusOn: "Focus on the following",
    avatarStudioQuestion1: "Could you explain how you plan to improve district traffic congestion?",
    avatarStudioQuestion2: "What is your plan for youth jobs and startup support?",
    avatarStudioQuestion3: "How will you address budget execution transparency concerns?",
    avatarStudioReceivedAt2h: "2 hours ago",
    avatarStudioReceivedAtYesterday: "Yesterday",
    avatarStudioReceivedAt2DaysAgo: "2 days ago",
    avatarStudioQuestion3Answer: "We will publish a quarterly public dashboard and openly share post-pledge milestones with residents.",
    avatarStudioQuestion3Notes: "Approved key answer. Reuse for upcoming policy-related questions.",

    // Purchase page
    purchaseTitle: "Purchase",
    purchaseSubtitle: "Check current avatar token usage and upcoming plan/payment information.",
    purchaseLoadingUsage: "Loading usage...",
    purchaseErrorFallback: "Failed to load usage.",
    purchaseTabPayment: "Payment",
    purchaseTabUsage: "Usage",
    purchasePaymentComingSoon: "Payment and billing features are coming soon.",
    purchasePaymentComingSoonDetail: "Plan management and billing features will be provided in upcoming updates.",
    purchaseSectionChat: "Chat",
    purchaseSectionEmbedding: "Knowledge Embedding",
    purchaseSectionQueryEmbedding: "Query Embedding",
    purchaseTotalTokens: "Total Tokens",
    purchasePromptTokens: "Prompt Tokens",
    purchaseCompletionTokens: "Completion Tokens",
    purchaseTotalCalls: "Total Calls",
    purchaseEmbeddingTokens: "Knowledge Embedding Tokens",
    purchaseQueryEmbeddingTokens: "Query Embedding Tokens",
    purchaseGuidanceTotalTokens: "The combined total of prompt tokens and completion tokens used in avatar conversations. Used to display the overall scale of AI usage costs.",
    purchaseGuidancePromptTokens: "Token count of messages sent to the AI model, including system prompts and user questions. Longer prompts increase cost.",
    purchaseGuidanceCompletionTokens: "Token count of the text the avatar generates as answers to users. Longer answers use more completion tokens.",
    purchaseGuidanceTotalCalls: "Total number of independent interactions the avatar processed across all conversations.",
    purchaseGuidanceEmbeddingTokens: "Tokens used to convert uploaded knowledge files (PDF, DOCX, text) into vector embeddings. Charged once when knowledge documents are uploaded or modified.",
    purchaseGuidanceQueryEmbeddingTokens: "Tokens used to convert user messages into vectors during conversations. Used for knowledge base search and semantic context lookup, charged for each conversation turn.",
    purchaseEmpty: "No avatar usage recorded yet.",
    purchaseAvatarLabel: "Avatar",
    purchaseCallsLabel: "Calls",
    purchaseLastUsed: "Last Used",
    purchaseUnnamedAvatar: "Unnamed Avatar",

    // Token Top-up
    tokenTopUpTitle: "Token Top-up (Same for All Tiers)",
    tokenTopUpLoadingPlans: "Loading plans…",
    tokenTopUpNoPlans: "No top-up plans available at the moment.",
    tokenTopUpNoPlansDetail: "When the admin sets plans, they'll be shown here.",
    tokenTopUpEventBanner: "First Event Discount Applied · Limited until April",
    tokenTopUpToken: "Token",
    tokenTopUpDiscount: "{n}% off",
    tokenTopUpOff: "off",
    tokenTopUpComingSoonNote: "Plans are configured by the admin.",
    // Payment
    payBtnLabel: "Pay Now",
    payProcessing: "Processing…",
    paySuccess: "Payment Complete!",
    paySuccessTokens: "+{n} tokens added",
    paySuccessBalance: "Balance: {n} tokens",
    payError: "Payment failed",
    payCancel: "Payment cancelled",
    payHistoryTitle: "Payment History",
    payHistoryEmpty: "No payment history yet.",
    payHistoryDate: "Date",
    payHistoryItem: "Item",
    payHistoryAmount: "Amount",
    payHistoryStatus: "Status",
    payHistoryStatusPaid: "Paid",
    payHistoryStatusPending: "Pending",
    payHistoryStatusFailed: "Failed",
    payHistoryStatusCancelled: "Cancelled",
    payHistoryTotalPaid: "Total Paid",
    tokenTxTitle: "Token Transaction History",
    tokenTxEmpty: "No token transactions yet.",
    tokenTxDate: "Date",
    tokenTxDesc: "Description",
    tokenTxAmount: "Amount",
    tokenBalance: "Token Balance",
    tokenTabTx: "Token History",

    // Token Usage Widget
    tokenUsageTitle: "Token Usage",
    tokenUsageBreakdown: "Detailed Breakdown",
    tokenUsageLlmCalls: "LLM Call Count",
    tokenUsagePromptTokens: "Prompt Tokens",
    tokenUsageCompletionTokens: "Completion Tokens",
    tokenUsageLlmTotal: "LLM Total",
    tokenUsageEmbeddingTokens: "Embedding Tokens",
    tokenUsageQueryEmbedding: "Query Embedding",
    tokenUsagePlatformTokens: "Deducted Platform Tokens",
    tokenUsagePlatformTokensHint: "Actual deducted service token count (Input×1 · Cached Input×0.5 · Output×4 weighting applied)",
    tokenUsageTotalUsed: "Total Used",
    tokenUsageUsed: "Used Tokens",
    tokenUsagePurchased: "Purchased Tokens",
    tokenUsageRemaining: "Remaining Tokens",

    // Payment Info Box
    payInfoTitle: "Payment Information",
    payInfoSelectPackage: "Select Package",
    payInfoNormalPrice: "Regular Price",
    payInfoEventAmount: "Event Payment Amount",
    payInfoAmount: "Payment Amount",
    payGatewayLabel: "Payment Provider",
    payGatewayInicis: "KG Inicis",
    payGatewayInicisDesc: "Card only",
    payGatewayKpn: "Korea Payment Network (KPN)",
    payGatewayKpnDesc: "Card · Transfer · Simple Pay…",
    payMethodLabel: "Payment Method",
    payMethodCard: "Card",
    payMethodTransfer: "Bank Transfer",
    payMethodVirtualAccount: "Virtual Account",
    payMethodMobile: "Mobile",
    payMethodKakao: "KakaoPay",
    payMethodNaver: "NaverPay",
    payMethodToss: "TossPay",
    payMethodPayco: "PAYCO",
    payMethodSamsung: "SamsungPay",
    payVirtualAccountBank: "Virtual Account Bank",
    bankKookmin:  "KB Kookmin Bank",
    bankShinhan:  "Shinhan Bank",
    bankHana:     "Hana Bank",
    bankWoori:    "Woori Bank",
    bankNonghyup: "NH Nonghyup Bank",
    bankIbk:      "IBK Industrial Bank",
    bankKakao:    "KakaoBank",
    bankToss:     "TossBank",
    bankPost:     "Korea Post",
    bankSaemaul:  "Saemaul Geumgo",
    payPayerName: "Payer Name",
    payOptional: "Optional",
    payDone: "Done",
    payFullName: "Enter your name",
    payNoName: "No name",
    payPhoneLabel: "Phone Number",
    payPhonePlaceholder: "010-0000-0000",
    payNameRequired: "Please enter the payer's name.",
    payPhoneRequired: "Please enter a valid phone number.",
    payBtnMake: "Pay ₩{amount}",
    paySecure: "Secure Payment",
    paySSL: "SSL 256-bit",
    payPCI: "PCI DSS",
    payChannelNotConfigured: "Please set {envName} in .env.",

    // Payment History
    payHistoryGateway: "Gateway",
    payHistoryReceipt: "Receipt",
    payHistoryReceiptTitle: "Download Receipt",
    payHistoryReceiptFailTitle: "Download Failure Record",
    payExportExcel: "Download Excel",
    payLoadMore: "Load More",
    payHistoryTotalPayment: "Total Payment",
    tokenTxType: "Type",
    tokenTxVisitor: "Visitor",
    tokenTxTokens: "Tokens",

    // Chat History
    chatHistory: "Chat History",
    chatHistoryTotalUsers: "visitors",
    chatHistorySearch: "Search by name or email…",
    chatHistoryNoUsers: "No conversation history",
    chatHistorySelectUser: "Select a visitor to view conversation",
    chatHistoryMsgs: "messages",
    chatHistoryNoMessages: "No messages",
    chatHistoryLoadMore: "Load earlier messages",
};
